// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEc6wWdOIOoybydBVJ2M8MWx6KPTjBtf8',
    appId: '1:1073530020881:web:5a64671d65d4b27b6a3db0',
    messagingSenderId: '1073530020881',
    projectId: 'chatbot-155c5',
    authDomain: 'chatbot-155c5.firebaseapp.com',
    storageBucket: 'chatbot-155c5.appspot.com',
    measurementId: 'G-94YM3G6JWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3L4LzadAwy9YkghIXAK7xUOscYPE-9w',
    appId: '1:1073530020881:android:7fc5face1cf6f8966a3db0',
    messagingSenderId: '1073530020881',
    projectId: 'chatbot-155c5',
    storageBucket: 'chatbot-155c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJKJMYvRZnm10UWyhjhU3anGEEc3AJwI',
    appId: '1:1073530020881:ios:24fb43e1f8876d2f6a3db0',
    messagingSenderId: '1073530020881',
    projectId: 'chatbot-155c5',
    storageBucket: 'chatbot-155c5.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJKJMYvRZnm10UWyhjhU3anGEEc3AJwI',
    appId: '1:1073530020881:ios:24fb43e1f8876d2f6a3db0',
    messagingSenderId: '1073530020881',
    projectId: 'chatbot-155c5',
    storageBucket: 'chatbot-155c5.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEc6wWdOIOoybydBVJ2M8MWx6KPTjBtf8',
    appId: '1:1073530020881:web:d71127408abe809a6a3db0',
    messagingSenderId: '1073530020881',
    projectId: 'chatbot-155c5',
    authDomain: 'chatbot-155c5.firebaseapp.com',
    storageBucket: 'chatbot-155c5.appspot.com',
    measurementId: 'G-SLJHHCEYK7',
  );
}
